name: index
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0' # Puedes ajustar esto a tu versión de SDK de Dart

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  # --- PAQUETES DE FIREBASE ---
  # El paquete principal para conectar Firebase
  firebase_core: ^3.1.1
  # El paquete para la base de datos Cloud Firestore
  cloud_firestore: ^5.0.2
  # El paquete para Autenticación (Login/Registro)
  firebase_auth: ^5.1.1 
  # --------------------------

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true